### PR TITLE
Enable blank issues

### PR DESCRIPTION
**Pull request by kylebarron**
I was planning to create a new issue to discuss whether arrow layers should accept Table or RecordBatch input. But currently the only way to create an issue is to fill out the full bug template.

### CODE REVIEW

**Comment by ibgreen** [comment]
This is intentional. For repo hygiene reasons we refer non-confirmed bugs to the discussions tab.

**Comment by kylebarron** [comment]
Can we mirror upstream deck.gl and have a feature request template? https://github.com/visgl/deck.gl/blob/master/.github/ISSUE_TEMPLATE/feature-request.yml

**Comment by ibgreen** [comment]
Well, the thinking was that this repo contains a bunch of modules without active maintainers - so having a "submit feature request" like in deck seems disingenuous, it sends the wrong message, and we'll end up with a ton of feature requests in the issues tab that most likely won't get addressed unless some random contributor picks them up.

If opening a feature request in discussions doesn't work perhaps we need to reconsider.

**Comment by kylebarron** [comment]
I like discussions for Q&A, but I don't like discussions for bugs or feature requests because they don't show interlinking as easily. Whenever you reference an issue or PR from any other issue on GitHub, you see from the target that it was linked to by the source PR. Discussions don't do that, and so it's harder to follow the graph of interconnected work.

**Comment by ibgreen** [comment]
Replaced by #144

**Comment by ibgreen** [comment]
Feature proposals have been added.

**Pull request closed without merging**
